title: instanceML
description: Un recorido por el aprendizaje de Machine Learning.
show_downloads: true
google_analytics:

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
theme: jekyll-theme-slate
markdown: kramdown

